name: irontech_nutrihierro
description: "App móvil IronTech NutriHierro para prevención de anemia infantil."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Fase 1: Enrutamiento y Estado
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.0

  # Fases 2 y 5: Firebase (Backend, Storage y DB offline-first)
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.0.0

  # Fases 3 y 4: UI, Imágenes y Texto
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_markdown: ^0.7.1 

  # Fase 5: Cámara
  image_picker: ^1.1.2

  # Fase 6: Notificaciones Locales (Offline)
  flutter_local_notifications: ^17.1.2
  uuid: ^4.5.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
